#ifndef AQ_SERIAL_STATEMACHINE_H_
#define AQ_SERIAL_STATEMACHINE_H_

typedef enum tagSerialFsm_States
{
	ST_WAITFOR_PACKETSTART		= 0,
	ST_RECEIVE_PACKETPAYLOAD	= 1,
	ST_RETRY_RECEIVEPAYLOAD		= 2,
	ST_VALIDATE_PACKETPAYLOAD   = 3,
	ST_ERROR_OCCURRED			= 4,
	ST_TERMINATE				= 5
}
SerialFsm_States;

#endif // AQ_SERIAL_STATEMACHINE_H_
